### ISSUE TITLE
Border around slider handle

### ISSUE THREAD

**Issue by zywind** [simeydotme/jQuery-ui-Slider-Pips#23]
There is a border around the slider handle when focused. In the css code, the following lines are supposed to remove that border, but it doesn't work. I think .ui-slider-float should be changed to .ui-slider.

``` css
.ui-slider-float .ui-slider-handle:focus,
.ui-slider-float .ui-slider-handle:focus .ui-slider-tip,
.ui-slider-float .ui-slider-handle:focus .ui-slider-tip-label {
    outline: none;
}
```
